-- MySQL Script generated by MySQL Workbench
-- Sun Aug 24 16:58:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema budgetlance
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema budgetlance
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `budgetlance` DEFAULT CHARACTER SET utf8mb4 ;
USE `budgetlance` ;

-- -----------------------------------------------------
-- Table `budgetlance`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `budgetlance`.`usuario` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nm_usuario` VARCHAR(50) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `senha` CHAR(16) NOT NULL,
  `tipo_usuario` ENUM('usuario', 'adm') NOT NULL DEFAULT 'usuario',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `budgetlance`.`categoria_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `budgetlance`.`categoria_servico` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_usuario` BIGINT(20) NOT NULL,
  `nm_servico` VARCHAR(35) NOT NULL,
  `desc_servico` VARCHAR(240) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `categoria_servico_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `budgetlance`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `budgetlance`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `budgetlance`.`cliente` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_usuario` BIGINT(20) NOT NULL,
  `nm_cliente` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(25) NULL DEFAULT NULL,
  `email` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `cliente_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `budgetlance`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `budgetlance`.`orcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `budgetlance`.`orcamento` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_cliente` BIGINT(20) NOT NULL,
  `id_usuario` BIGINT(20) NOT NULL,
  `id_cs` BIGINT(20) NOT NULL,
  `nm_orcamento` VARCHAR(50) NOT NULL,
  `desc_orcamento` VARCHAR(240) NOT NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  `prazo` DATETIME NOT NULL,
  `status` ENUM('pendente', 'enviado', 'aprovado', 'recusado', 'cancelado') NOT NULL DEFAULT 'pendente',
  PRIMARY KEY (`id`),
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_cs` (`id_cs` ASC) VISIBLE,
  CONSTRAINT `orcamento_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `budgetlance`.`cliente` (`id`),
  CONSTRAINT `orcamento_ibfk_2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `budgetlance`.`usuario` (`id`),
  CONSTRAINT `orcamento_ibfk_3`
    FOREIGN KEY (`id_cs`)
    REFERENCES `budgetlance`.`categoria_servico` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
